apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: johne8ns-johne8ns-poi-map-app-dev
  annotations:
    argocd/app-name: johne8ns-johne8ns-poi-map-app-dev
    backstage.io/kubernetes-id: johne8ns-johne8ns-poi-map-app-dev
    backstage.io/kubernetes-namespace: johne8ns
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=johne8ns-johne8ns-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus2/johne8ns-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/dev-pipelines/ns/johne8ns/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/k8s/ns/johne8ns/deployments/johne8ns-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23blues.6mbu.p1.openshiftapps.com/#https://github.com/Summit23Janus2/johne8ns-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://johne8ns-poi-map-app-johne8ns.apps.summit23blues.6mbu.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/johne8"
  system: workshop-system-johne8ns
  consumesApis:
    - gateway-api-johne8ns
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-johne8ns
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/johne8"
